---
- hosts: "simon-dev"
  name: Setup and configure developer server
  serial: 1
  gather_facts: false
  any_errors_fatal: true
  become_user: root

  vars_files:
    - ../secrets.yml

  pre_tasks:
    - name: Ensure python is installed
      raw: test -e /usr/bin/python3 || (apt-get -y update && apt-get -y install python)
      changed_when: false
    - setup: # aka gather_facts

  tasks:
    - import_tasks: ../tasks/common.yml
    - import_tasks: ../tasks/dev-common.yml
    - import_tasks: ../tasks/dev-platform.yml
    - import_tasks: ../tasks/php.yml
    #- import_tasks: ../tasks/dev-sql-server.yml
    - import_tasks: ../tasks/containers.yml
    #- import_tasks: ../tasks/mariadb.yml
