---
#
# Common tasks performed on all hosts regardless of their intended role(s)
#

- name: Update apt
  become: yes
  apt:
    update_cache: yes

- name: Install system packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - python3-pip
    - curl
    - wget
    - zip

