---
#
# Installs Container tools - Podman, etc
#

- name: Add Podman release key
  become: yes
  apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/Release.key
    state: present

- name: Add Podman Apt repo
  become: yes
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /"
    filename: "kubic_podman_ubuntu_{{ ansible_distribution_version }}"
    state: present

- name: Install Podman
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - podman
