---
#
# Common tasks performed on all dev environment hosts
#

- name: Install common dev packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - jq

- name: Check for dotfiles
  stat:
    path: ~/dotfiles
  register: dotfiles_path

- name: Download dotfiles
  git:
    repo: https://github.com/simon-downes/dotfiles.git
    dest: ~/dotfiles
  when: dotfiles_path.stat.exists == False

- name: Get bashrc status
  stat:
    path: ~/.bashrc
  register: bashrc

- name: Install dotfiles
  shell: "~/dotfiles/bin/install"
  when: bashrc.stat.islnk == False
