---
#
# Installs command-line tools for SQL Server
#

- name: Add Microsoft's GPG key
  become: yes
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Microsoft Apt repo
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main"
    state: present

- name: Install Microsoft ODBC library and CLI tools
  become: yes
  package:
    name: "{{ item }}"
    state: "present"
  loop:
    - msodbcsql17
    - mssql-tools
  environment:
        ACCEPT_EULA: Y

- name: Create symlinks to SQL Server CLI tools
  become: yes
  file:
    src: "/opt/mssql-tools/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - bcp
    - sqlcmd
