---
#
# Config tools geared toward platform/infrastructure development
#

# check if ansible is already installed
- command: dpkg-query -W 'ansible'
  ignore_errors: True
  register: is_ansible

- name: Ensure Ansible PPA exists
  become: yes
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
  when: is_ansible is failed

- name: Install Ansible
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - ansible
  when: is_ansible is failed

- name: Install Terraform
  become: yes
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/terraform

- name: Install AWS CLI v2
  become: yes
  shell:
    cmd: "cd /tmp && curl \"https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip\" -o \"awscliv2.zip\" && unzip awscliv2.zip && sudo ./aws/install && rm ./awscliv2.zip && rm -rf ./aws"
    creates: /usr/local/bin/aws
