---
#
# Installs PHP 7.3, Composer, PHP Unit and SQLSRV driver
#

- name: Ensure PHP PPA exists
  become: yes
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - php7.4-cli
    - php7.4-fpm
    - php7.4-bcmath
    - php7.4-curl
    - php7.4-dev
    - php7.4-gd
    - php7.4-json
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-pgsql
    - php7.4-sqlite3
    - php7.4-xml
    - php7.4-zip
    - php-pear

- name: Set composer_path if not defined
  set_fact:
    composer_path: /usr/local/bin/composer
  when: composer_path is not defined

- name: Check for Composer
  stat:
    path: "{{ composer_path }}"
  register: composer_bin

- name: Get Composer installer signature
  uri:
    url: https://composer.github.io/installer.sig
    return_content: true
  register: composer_installer_signature
  when: not composer_bin.stat.exists

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not composer_bin.stat.exists

- name: Run Composer installer
  become: yes
  command:
    cmd: php composer-installer.php
    chdir: /tmp
  when: not composer_bin.stat.exists

- name: Move Composer into globally-accessible location
  become: yes
  command:
    cmd: mv /tmp/composer.phar {{ composer_path }}
    #creates={{ composer_path }}
  when: not composer_bin.stat.exists

- name: Ensure Composer is the latest version
  become: yes
  shell: "{{ composer_path }} self-update"
  when: composer_bin.stat.exists == True

- name: Download phpunit (9.x)
  become: yes
  get_url:
    url: https://phar.phpunit.de/phpunit-9.phar
    dest: /usr/local/bin/phpunit
    mode: 0755
